sudo: required
before_install:
    - sudo apt-add-repository -y ppa:fish-shell/release-2
    - sudo apt-get update
    - sudo apt-get -y install fish
    - fish --version
    - curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher
    - fish -c "fisher --version"
script:
    - fish -c "fisher add kobanyan/ghr@$TRAVIS_BRANCH"
    - cat test/test.fish | fish
