sudo: required
before_install:
    - sudo apt-add-repository -y ppa:fish-shell/release-2
    - sudo apt-get update
    - sudo apt-get -y install fish
script:
    - curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher
    - fish -c "fisher --version"
    - fish -c "fisher install kobanyan/ghr"
    - cat test.fish | fish
