sudo: required
before_install:
    - sudo apt-add-repository -y ppa:fish-shell/release-3
    - sudo apt-get update
    - sudo apt-get -y install fish
    - fish --version
    - fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"
    - fish -c "fisher --version"
script:
    - fish -c "fisher install jorgebucaran/getopts.fish americanhanko/fish-spin kobanyan/ghr"
    - cat test/test.fish | fish
