complete -c ghr -x -d "Download archive from github releases" -a "\t"
complete -c ghr -f -s h -l help -d "Show usage help."
complete -c ghr -f -s n -l name -d "Save binary as <name>."
complete -c ghr -f -s r -l repo -d "Github repository <owner/repo>."
complete -c ghr -f -s v -l version -d "Download target <version>. Use 'latest' if empty."
